# Generated by Django 2.1.3 on 2018-12-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steppsresult',
            old_name='freq_h',
            new_name='freq_high',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='freq_l',
            new_name='freq_low',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='freq_m',
            new_name='freq_medium',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='keywords',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='px_h',
            new_name='px_high',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='px_l',
            new_name='px_low',
        ),
        migrations.RenameField(
            model_name='steppsresult',
            old_name='px_m',
            new_name='px_medium',
        ),
    ]
