# Generated by Django 2.1.3 on 2018-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181208_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppsresult',
            name='label',
            field=models.CharField(default='', max_length=2),
        ),
    ]
