# Generated by Django 2.1.3 on 2018-12-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_classificationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('follower_count', models.IntegerField()),
                ('taken_at', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('caption_text', models.TextField()),
                ('time_frame', models.IntegerField()),
                ('engagement', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
